"""
init_deep_research_db.py — Deep Research reports table.

Stores frontier-model research dossiers generated by /api/deep-research/run.
Admin-only feature; rows are immutable once written so users can compare
different models (Gemini 3 Pro vs Claude Opus vs GPT-5.5) on the same stock.
"""
import os
import psycopg2
from psycopg2.extras import RealDictCursor
from database.database import get_db_port


def get_db():
    try:
        from database.database import get_db as _get_db
        return _get_db()
    except (ImportError, ModuleNotFoundError):
        db_url = os.environ.get("DATABASE_URL")
        if db_url:
            return psycopg2.connect(db_url, cursor_factory=RealDictCursor)
        return psycopg2.connect(
            host=os.getenv('DB_HOST'),
            database=os.getenv('DB_NAME', 'postgres'),
            user=os.getenv('DB_USER', 'postgres'),
            password=os.getenv('DB_PASSWORD'),
            port=get_db_port(),
            sslmode='require',
            cursor_factory=RealDictCursor
        )


def init_deep_research_table():
    conn = get_db()
    try:
        cursor = conn.cursor()
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS deep_research_reports (
                id SERIAL PRIMARY KEY,
                symbol TEXT NOT NULL,
                company_name TEXT,
                mode TEXT NOT NULL,
                model_used TEXT NOT NULL,
                window_start DATE,
                window_end DATE,
                content_md TEXT NOT NULL,
                report_json JSONB,
                dossier_json JSONB,
                citations_json JSONB,
                web_queries_json JSONB,
                input_tokens INTEGER DEFAULT 0,
                output_tokens INTEGER DEFAULT 0,
                latency_ms INTEGER DEFAULT 0,
                created_by TEXT,
                created_at TIMESTAMP DEFAULT NOW()
            )
        ''')
        # Idempotent backfill for environments where the table predates the
        # citations columns (the upgrade ships them in the same release).
        cursor.execute('ALTER TABLE deep_research_reports ADD COLUMN IF NOT EXISTS citations_json JSONB')
        cursor.execute('ALTER TABLE deep_research_reports ADD COLUMN IF NOT EXISTS web_queries_json JSONB')
        # Structured verdict extracted from the markdown — lets us filter/aggregate
        # across reports without parsing markdown each time.
        # Shape: { stance, conviction, headline, alpha_pp, pe_rerating_pct,
        #          score_setup, score_end, score_delta, top_risk, ... }
        cursor.execute('ALTER TABLE deep_research_reports ADD COLUMN IF NOT EXISTS verdict_json JSONB')
        # report_json holds the structured PDF-renderable shape (added in the
        # PDF-export feature). Older rows have NULL here and will return 409
        # from /report/<id>/pdf with a "regenerate to enable PDF" message.
        cursor.execute('ALTER TABLE deep_research_reports ADD COLUMN IF NOT EXISTS report_json JSONB')
        # Materialised PDF — rendered once at persist time so the same bytes
        # serve every download and the frontend iframe view. Lazy-filled on
        # first download for rows that predate this column.
        cursor.execute('ALTER TABLE deep_research_reports ADD COLUMN IF NOT EXISTS pdf_bytes BYTEA')
        cursor.execute('ALTER TABLE deep_research_reports ADD COLUMN IF NOT EXISTS pdf_generated_at TIMESTAMPTZ')

        cursor.execute('CREATE INDEX IF NOT EXISTS idx_deep_research_symbol ON deep_research_reports (symbol, created_at DESC)')
        cursor.execute('CREATE INDEX IF NOT EXISTS idx_deep_research_created ON deep_research_reports (created_at DESC)')
        cursor.execute('CREATE INDEX IF NOT EXISTS idx_deep_research_user ON deep_research_reports (created_by, created_at DESC)')
        cursor.execute('CREATE INDEX IF NOT EXISTS idx_deep_research_verdict ON deep_research_reports ((verdict_json->>\'stance\'))')

        conn.commit()
        print("✅ deep_research_reports table ready")
    except Exception as e:
        print(f"⚠️ Deep Research table init: {e}")
        conn.rollback()
    finally:
        conn.close()


if __name__ == '__main__':
    init_deep_research_table()
